In [ ]:
from numpy import array
from keras_preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.embeddings import Embedding

In [ ]:
#Define Documents

mysent = ['do you comet to see me', 'Seneca is a good college', 'that is yours', 'Do you want dinner', 'do you like it', 'where are you from', 'thank you i am good', 'how dare you say that?', 'How are you', 'How is the weather', 'how is your pet', 'i am fine', 'i live in toronto', 'i have no dog']


In [ ]:
# Categorize and define class labels

mysentlabels = array([1,0, 0,1,1,1, 0,1,1,1,1,0,0,0])

In [ ]:
# Encoding of documents

myvocabsiz = 40                       # max number of different words
encodsent = [one_hot(i, myvocabsiz) for i in mysent]     # Encoding
print(encodsent)
type(encodsent)

[[17, 4, 9, 20, 36, 30], [34, 35, 10, 13, 19], [38, 35, 6], [17, 4, 9, 7], [17, 4, 20, 25], [28, 37, 4, 31], [30, 4, 9, 23, 13], [8, 26, 4, 3, 38], [8, 37, 4], [8, 35, 8, 26], [8, 35, 5, 26], [9, 23, 22], [9, 4, 22, 9], [9, 37, 30, 19]]


list

In [ ]:
# Padding documents to mas length 5

length = 5
padmysent = pad_sequences(encodsent, maxlen = length, padding = 'pre')
print(padmysent)

[[ 4  9 20 36 30]
 [34 35 10 13 19]
 [ 0  0 38 35  6]
 [ 0 17  4  9  7]
 [ 0 17  4 20 25]
 [ 0 28 37  4 31]
 [30  4  9 23 13]
 [ 8 26  4  3 38]
 [ 0  0  8 37  4]
 [ 0  8 35  8 26]
 [ 0  8 35  5 26]
 [ 0  0  9 23 22]
 [ 0  9  4 22  9]
 [ 0  9 37 30 19]]


In [ ]:
# Building model

mymodel = Sequential()             
mymodel.add(Embedding(input_dim=myvocabsiz, output_dim = 8, input_length = length))
mymodel.add(Flatten())          # input layer
#mymodel.add(Dense(8, activation = 'sigmoid'))         # hidden layer
mymodel.add(Dense(1, activation = 'sigmoid'))         # output layer
mymodel.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
print(mymodel.summary())
mymodel.fit(padmysent, mysentlabels, epochs = 100)


Model: "sequential_46"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_45 (Embedding)    (None, 5, 8)              320       
                                                                 
 flatten_44 (Flatten)        (None, 40)                0         
                                                                 
 dense_63 (Dense)            (None, 1)                 41        
                                                                 
Total params: 361
Trainable params: 361
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/100
1/1 [==============================] - 1s 789ms/step - loss: 0.6998 - accuracy: 0.3571
Epoch 2/100
1/1 [==============================] - 0s 7ms/step - loss: 0.6973 - accuracy: 0.4286
Epoch 3/100
1/1 [==============================] - 0s 9ms/step - loss: 0.6947 - accuracy: 0.4286
Epoch 4/100
1/1 [====

In [ ]:
# Predicting

topredict = ['where are you from', 'are you willing to go', 'do you study in seneca', 'i am james', 'i am very proud of you', 'how tall are you', 'i am short']


vocab_size = 40
encoded = [one_hot(i, vocab_size) for i in topredict]
print(encoded)

[[28, 37, 4, 31], [37, 4, 30, 20, 16], [17, 4, 38, 22, 34], [9, 23, 39], [9, 23, 3, 37, 30, 4], [8, 26, 37, 4], [9, 23, 17]]


In [ ]:
max_length = 5
mypaded = pad_sequences(encoded, maxlen= max_length, padding='pre')
print(mypaded)

[[ 0 28 37  4 31]
 [37  4 30 20 16]
 [17  4 38 22 34]
 [ 0  0  9 23 39]
 [23  3 37 30  4]
 [ 0  8 26 37  4]
 [ 0  0  9 23 17]]


In [ ]:
ypred = mymodel.predict(mypaded )
print(ypred)

[[0.7037643 ]
 [0.5486569 ]
 [0.47848997]
 [0.3926739 ]
 [0.58431274]
 [0.7117493 ]
 [0.3988344 ]]


In [ ]:
import numpy as np
print(np.around(ypred))

[[1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]]
